/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageRequest {
  chatId?: string | undefined;
  content?: string;
  messageType?: string;
  receiverId?: string;
  senderId?: string;
}
